import { Link } from 'react-router-dom'

const SCORE_FACTORS = [
  {
    title: 'Token Verification',
    points: 22,
    maxPoints: 25,
    tone: 'cyan',
    note: 'Unique vendor token validates the feedback path.',
  },
  {
    title: 'Payment Proof',
    points: 20,
    maxPoints: 20,
    tone: 'teal',
    note: 'Order and payment status are checked against records.',
  },
  {
    title: 'AI Behavior Score',
    points: 20,
    maxPoints: 25,
    tone: 'green',
    note: 'Typing rhythm, edits, and originality are analyzed.',
  },
  {
    title: 'Device Pattern',
    points: 13,
    maxPoints: 15,
    tone: 'purple',
    note: 'Hashed device repetition helps detect abuse patterns.',
  },
  {
    title: 'Context Depth',
    points: 12,
    maxPoints: 15,
    tone: 'amber',
    note: 'Specific and balanced feedback receives higher trust.',
  },
]

function toPercent(points, maxPoints) {
  if (!maxPoints) return 0
  return Math.max(0, Math.min(100, Math.round((points / maxPoints) * 100)))
}

function metricFillClass(tone) {
  if (tone === 'cyan') return 'lpMetricFill lpMetricFill--cyan'
  if (tone === 'teal') return 'lpMetricFill lpMetricFill--teal'
  if (tone === 'green') return 'lpMetricFill lpMetricFill--green'
  if (tone === 'purple') return 'lpMetricFill lpMetricFill--purple'
  return 'lpMetricFill lpMetricFill--amber'
}

function FlowIcon({ kind }) {
  if (kind === 'invoice') {
    return (
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <rect x="4" y="5" width="16" height="14" rx="2" stroke="currentColor" strokeWidth="2" />
        <path d="M8 10h8M8 14h5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      </svg>
    )
  }

  if (kind === 'payment') {
    return (
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <rect x="3" y="6" width="18" height="12" rx="2" stroke="currentColor" strokeWidth="2" />
        <path d="M3 10h18" stroke="currentColor" strokeWidth="2" />
        <circle cx="16.5" cy="14" r="1.5" fill="currentColor" />
      </svg>
    )
  }

  if (kind === 'delivery') {
    return (
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="M4 8h10v7H4zM14 10h3l3 3v2h-2" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        <circle cx="8" cy="17" r="1.5" fill="currentColor" />
        <circle cx="18" cy="17" r="1.5" fill="currentColor" />
      </svg>
    )
  }

  if (kind === 'feedback') {
    return (
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="M4 6h16v10H9l-4 3V6z" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" />
        <path d="M8 10h8M8 13h6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      </svg>
    )
  }

  if (kind === 'score') {
    return (
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="M4 18V8M10 18V6M16 18v-4M20 18V9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      </svg>
    )
  }

  if (kind === 'anchor') {
    return (
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="M12 3v7M9 6h6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <path d="M6 13a6 6 0 0012 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <path d="M8 13H4m16 0h-4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      </svg>
    )
  }

  return null
}

const FLOW_STEPS = [
  {
    title: 'Vendor Creates Invoice',
    detail: 'Order, invoice, and feedback token are generated by Trusty.',
    icon: 'invoice',
  },
  {
    title: 'Payment Confirmed',
    detail: 'Payment state is recorded and linked with the order.',
    icon: 'payment',
  },
  {
    title: 'Delivery Completed',
    detail: 'Customer receives a feedback link after delivery status updates.',
    icon: 'delivery',
  },
  {
    title: 'Feedback Submitted',
    detail: 'No forced login. Trusty collects only privacy-safe signals.',
    icon: 'feedback',
  },
  {
    title: 'Trust Score Generated',
    detail: 'Rule-based scoring plus bounded adjustments compute final trust.',
    icon: 'score',
  },
  {
    title: 'Blockchain Anchored',
    detail: 'SHA-256 metadata hash and tx reference create tamper-evident proof.',
    icon: 'anchor',
  },
]

const TECH_BLOCKS = [
  {
    title: 'Scoring Engine',
    body: 'Transparent scoring logic in Node.js combines token, payment, behavior, device, and context signals.',
  },
  {
    title: 'IP Risk Intelligence',
    body: 'GeoLite2 and IPQualityScore enrich risk context while only hashed IP and coarse location are stored.',
  },
  {
    title: 'Embedding Similarity',
    body: 'Python embedding service with FAISS detects near-duplicate feedback and supports duplicate adjustment.',
  },
  {
    title: 'Blockchain Proof Layer',
    body: 'Only metadata hash and transaction reference are anchored; raw feedback text is never written on-chain.',
  },
]

export function HowItWorksPage() {
  const totalScore = SCORE_FACTORS.reduce((acc, factor) => acc + factor.points, 0)

  return (
    <div className="hiwPage">
      <section className="hiwHero hiwSingle revealUp" style={{ '--reveal-delay': '0ms' }}>
        <div className="hiwInner hiwInner--narrow hiwHeroIntro">
          <div className="hiwPill">Explainable Trust Technology</div>
          <h1>How We Build Trust Without Invading Privacy</h1>
          <p>
            Every review follows a clear verification workflow. Fast for users, explainable for teams,
            and privacy-safe by design.
          </p>
        </div>

        <div className="hiwInner hiwSingleBlock">
          <div className="hiwSectionHead">
            <h2>Explainable Trust Scores</h2>
            <p>
              Every feedback receives a transparent trust score calculated from independent
              explainable signals. No hidden algorithms.
            </p>
          </div>

          <article className="lpScorePanel">
            <div className="lpScoreLeft">
              <div className="lpScoreDial" style={{ '--progress': `${totalScore}%` }}>
                <div className="lpScoreDialInner">
                  <div className="lpScoreDialValue">{totalScore}</div>
                  <div className="lpScoreDialLabel">High Trust</div>
                </div>
              </div>
              <h3>Sample Feedback Score</h3>
              <p>Based on Trusty multi-signal analysis</p>
            </div>

            <div className="lpScoreRight">
              {SCORE_FACTORS.map((factor) => (
                <div className="lpMetric" key={factor.title}>
                  <div className="lpMetricHead">
                    <span>{factor.title}</span>
                    <span>{factor.points} pts</span>
                  </div>
                  <div className="lpMetricTrack">
                    <div
                      className={metricFillClass(factor.tone)}
                      style={{ width: `${toPercent(factor.points, factor.maxPoints)}%` }}
                    />
                  </div>
                  <p className="lpMetricNote">{factor.note}</p>
                </div>
              ))}

              <div className="lpMetricTotal">
                <span>Total Trust Score</span>
                <strong>{totalScore}/100</strong>
              </div>
            </div>
          </article>
        </div>

        <div className="hiwInner hiwInner--steps hiwSingleBlock">
          <div className="hiwSectionHead hiwSectionHead--center">
            <h2>How It Works</h2>
            <p>From invoice creation to blockchain anchor in a simple, auditable workflow.</p>
          </div>

          <div className="hiwStepsList">
            {FLOW_STEPS.map((step, index) => (
              <article className="hiwStepCard" key={step.title}>
                <div className="hiwStepNumber">{index + 1}</div>
                <div className="hiwStepIcon" aria-hidden="true">
                  <FlowIcon kind={step.icon} />
                </div>
                <div className="hiwStepBody">
                  <h3>{step.title}</h3>
                  <p>{step.detail}</p>
                </div>
                <div className="hiwStepArrow" aria-hidden="true">
                  →
                </div>
              </article>
            ))}
          </div>
        </div>

        <div className="hiwInner hiwSingleBlock">
          <div className="hiwSectionHead">
            <h2>Core Technology Used</h2>
            <p>Only the components actively used in this project’s verification pipeline.</p>
          </div>

          <div className="hiwTechGrid">
            {TECH_BLOCKS.map((item) => (
              <article className="hiwTechCard" key={item.title}>
                <div className="hiwTechDot" aria-hidden="true" />
                <h3>{item.title}</h3>
                <p>{item.body}</p>
              </article>
            ))}
          </div>

          <div className="hiwActions">
            <Link className="lpBtn lpBtn--primary" to="/public">
              View Public Feedback
            </Link>
            <Link className="lpBtn lpBtn--outline" to="/transparency">
              Read Transparency Notes
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
